name: Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --noconfirm --onefile --name "CS2 Triggerbot" --icon "./build/icon.ico" --version-file "./build/version.txt" --add-data "./classes;classes/" --add-data "./classes/icon.png;." ./main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: CS2-Triggerbot-Build
          path: dist/CS2 Triggerbot.exe
