name: Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    name: Build and Test on Windows
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run PyQt6 Application Tests
        run: |
          python -m unittest discover -s tests

      - name: Build Executable (Optional)
        run: |
          pip install pyinstaller pyarmor
          pyinstaller --onefile main.py
        env:
          PATH: C:\Python${{ matrix.python-version }};${{ env.PATH }}

      - name: Upload Build Artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: cs2-triggerbot-windows
          path: dist/main.exe
