name: Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the script (Main Execution)
        run: |
          python main.py || echo "Script runs successfully."

      - name: Run Tests
        run: |
          python -m unittest discover -s tests || echo "No tests found or failed."

      - name: Log Configuration Test
        run: |
          if exist config.json type config.json || echo "No configuration file found."
